version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password!
      POSTGRES_DB: robo-pantry-db
    ports:
      - 5433:5432